### ISSUE TITLE
What determines which toolchain architectures are "dummies"?

### ISSUE THREAD

**Issue by seh** [5h4d0w4rt/rules_prometheus#1]
At present, the only toolchain architecture  fed into `declare_toolchains_prod` [is "darwin-amd64,"](https://github.com/5h4d0w4rt/rules_prometheus/blob/12dc9b54de7dd71121ef895388491c5f87255713/prometheus/internal/BUILD#L57-L59) covering most machines running macOS. By contrast, [the rest of the known architectures are fed into `declare_toolchains_dummy`](https://github.com/5h4d0w4rt/rules_prometheus/blob/12dc9b54de7dd71121ef895388491c5f87255713/prometheus/internal/BUILD#L63-L90)—notably, the popular "linux-amd64."

Is it viable to promote some of the "dummy" architectures to the "prod" set? Are most of them demoted due to lack of testing thus far? In particular, I'd like to be able to use these rules on machines running Linux. [The published release archive for Prometheus for "darwin-amd64"](https://github.com/prometheus/prometheus/releases/download/v2.31.0-rc.1/prometheus-2.31.0-rc.1.darwin-amd64.tar.gz) does include the _promtool_ tool. It looks like we'd need a way to [populate the "exec_compatible_with" and "target_compatible_with" attributes of the `toolchain` rule](https://github.com/5h4d0w4rt/rules_prometheus/blob/12dc9b54de7dd71121ef895388491c5f87255713/prometheus/internal/toolchain.bzl#L59-L66).

Please advise on whether you'd accept a patch promoting this architecture—and any others that might be ready for use.

**Comment by 5h4d0w4rt** [comment]
hey @seh! 

Thanks for the contribution with the PR, but I was almost done on my local branch so figured i will finish my changes but i have incorporated your code on stardoc, probably should test the repo more as a downstream :)

https://github.com/5h4d0w4rt/rules_prometheus/actions/runs/1402466534 build now works on ubuntu and i will add matrix build too for different CPUs

If you have any needs on particular features of the rules not in the TODO list please tell me

**Comment by 5h4d0w4rt** [comment]
Rolled out new release, try it!
https://github.com/5h4d0w4rt/rules_prometheus/releases/tag/0.0.4

**Comment by seh** [comment]
It works! Thank you.

Should we close this issue? Are all toolchain architectures supported as of this latest release?

**Comment by 5h4d0w4rt** [comment]
> It works! Thank you.

Excellent! :)

> Should we close this issue? 
Yep

>Are all toolchain architectures supported as of this latest release?
They probably should, but most of them are not yet tested. I will add proper testing, but if build on ubuntu is of any indication, most popular binaries (and thus, more polished bazel architectures) should be detected proper right now.

LMK if there's anything else you need done by opening new issue :)
